### PR TITLE
Fix geneds being wrong for some courses

### LINKED ISSUE #180: `gen_ed` is wrong for `CCJS225`
https://api.umd.io/v1/courses/CCJS225

```json
"gen_ed": [
  [
    "DSHSDSSP",
    "SCIS"
  ]
],
```

should be
```json
"gen_ed": [
  [
    "DSHS",
    "SCIS",
  ],
  [
    "DSSP",
    "SCIS"
  ]
],
```

similarly for any course that allows you to choose between geneds, such as `HIST187`, `HIST200`, etc (scroll down https://app.testudo.umd.edu/soc/gen-ed/202108/DSHS to find a bunch).

### PR DESCRIPTION
**Pull request by tybug**
closes #180. 

The issue here is that we were using `.delete('General Education:'),`, which doesn't remove a substring from a string, but in fact takes a string of characters and removes each of these characters from the string. We got exceedingly lucky (or unlucky) in that this happened to give the desired behavior - removing the string `GenEd:` from the gened string - while also not removing any characters from actual geneds (no gened has a G or E in it. Note case matters, G and E were our only uppercase characters). 

However, this does mean that the string "or" was removed from all gened strings, so while CCJS225 says `DSHS or DSSP, SCIS`, we stored `DSHS DSSP, SCIS`.

Unfortunately, we now have wrong data in the database for years that can't be scraped any more. We can fix this issue going forward for all future and currently available semesters, but how should we deal with old semesters? I think it may be possible to reconstruct the original string (including `or`) from the (wrong) data we have, and thus replace our database entries with the proper values and fix this bug for all semesters, but I'm curious to hear thoughts on how we should proceed.

### CODE REVIEW

**Comment by DonIsaac** [comment]
Looks good, but could you add tests for this as well?

**Comment by tybug** [comment]
sure, will do in a bit

**Review by DonIsaac — APPROVED** [review]

**Comment by DonIsaac** [comment]
@tybug any updates?

**Comment by tybug** [comment]
Was just looking back at this as well - I'll need to re-convince myself this code is correct, but I'll take a look again.

**Comment by tybug** [comment]
going to just get this one in - I'm 95% sure it works as intended. can fix later if necessary.

**Pull request merged**
