### PR TITLE
Fix docs build

### LINKED ISSUE #41: Unable to run docs server locally
I've tried to run the docs server locally, but there seems to be a problem with the configuration with regards to the styles. Executing the make file results in:
`	
jekyll build -s src/ -d public/
Configuration file: src/_config.yml
            Source: src/
       Destination: public/
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.6.0 | Error:  No such file or directory @ rb_sysopen - /home/nick/dev/web/umdio/docs/src/css/main.scss
`

### PR DESCRIPTION
**Pull request by McIntireEvan**
* Jekyll now correctly builds the docs
* Fixed imports/config
* Remove trailing spaces in main.scss
* Fixes #41

### CODE REVIEW

**Comment by McIntireEvan** [comment]
@nyaculak @sdrozzy would love to have you guys test it out and make sure you can get the docs building and working on your end, too

**Comment by sdrozzy** [comment]
Clone the pull request and running into this error when running `jekyll serve`
```
Conversion error: Jekyll::Converters::Scss encountered an error while converting 'docs/src/css/main.scss':
                    File to import not found or unreadable: bourbon/bourbon. on line 1
jekyll 3.6.0 | Error:  File to import not found or unreadable: bourbon/bourbon. on line 1
```

**Comment by McIntireEvan** [comment]
Ah, I havn't been running `jekyll serve`, I've been running `make` and then serving with nginx. I'll see if I can find something that makes both methods work

**Comment by McIntireEvan** [comment]
Also it looks like we have an issue with the tests that arises from a shift in what the schedule of classes has up. I think we'll definately have to spend some time discussing better testing strategies

**Comment by sdrozzy** [comment]
@McIntireEvan I think either method to get the docs running is fine. I was just going off the `CONTRIBUTING.md` doc. Could you update that doc and I'll try again?

**Comment by McIntireEvan** [comment]
Ok, after a lot of messing with jekyll, I have it all working. You can do a `jekyll serve`, or `make run` to serve with Jekyll, or `make` and serve with nginx by just pointing it to the output dir. Just gotta update our docs and I'll push

**Comment by McIntireEvan** [comment]
As a note, I do know the css is messed up and I'll try to fix it before me merge this

**Comment by sdrozzy** [comment]
`jekyll serve` and `make run` both look good from my end

**Comment by McIntireEvan** [comment]
Gonna merge this so other people can run the docs when developing - also going to make a follow-up issue about the site css

**Pull request merged**
