### PR TITLE
Added dev:up and dev:down commands

### PR DESCRIPTION
**Pull request by DonIsaac**
- up(tasks): added `dev:up` and `dev:down` to start/stop the dev container environment, respectively
- docs(README): Updated `README.md` to include the tasks
- docs(README): Added some links to existing documentation

### CODE REVIEW

**Review by McIntireEvan — COMMENTED** [review]
Good change! Can you also update the readme to use this command?

You'll also have to rebase on the other PR I landed and fix merge conflicts, should be easy though

**Comment by DonIsaac** [comment]
@McIntireEvan merge conflicts fixed. I can indeed update the readme; would rather do it in another PR to avoid rebuilding, but I can do it in this one if you'd like

**Comment by McIntireEvan** [comment]
> 
> 
> @McIntireEvan merge conflicts fixed. I can indeed update the readme; would rather do it in another PR to avoid rebuilding, but I can do it in this one if you'd like

Avoid rebuilding what?

**Comment by DonIsaac** [comment]
> > @McIntireEvan merge conflicts fixed. I can indeed update the readme; would rather do it in another PR to avoid rebuilding, but I can do it in this one if you'd like
> 
> Avoid rebuilding what?

The application with Github actions. The CI runs on any changes, regardless if they're changes to documentation or not

**Pull request merged**
