### PR TITLE
Re Add Route for Bus V2

### PR DESCRIPTION
**Pull request by Josiassejod1**
Seems like Bus Controller V1 was intentionally left disabled because of COVID-19, reason why BUS WAS UNAVAILABLE message, this should add it back

### CODE REVIEW

**Comment by tybug** [comment]
I've touched up this pr, and removed `wrapRequest_v1` in favor of just `wrapRequest`, which is apparently all we needed to do to make this work.

**Review by tybug — APPROVED** [review]

**Comment by DonIsaac** [comment]
@tybug Looks good to me. Gonna merge this.

**Comment by Josiassejod1** [comment]
Have you seen this error before @tybug ?
Screen Shot 2021-06-21 at 9 51 48 AM

**Comment by tybug** [comment]
vaguely...but I can't find it now and I don't recall what the cause was.

(you should really join the discord for generic discussion instead of commenting on random issues: https://discord.gg/8gtEzgM7ay

**Pull request merged**
